<?php

return [
    'rfc' => '000',
    'brand' => [
        'name' => 'Athenas Boutique',
        'headline' => 'Accesorios accesibles para elevar tu look diario.',
        'subheadline' => 'Catalogo publico con compra directa por WhatsApp y carrito persistido en sesion.',
        'description' => 'Athenas Boutique ofrece aretes, anillos y collares con precios accesibles para ventas al detal. El pedido se prepara desde el carrito y se confirma directamente por WhatsApp.',
    ],
    'contact' => [
        'instagram' => 'athenasboutique1',
        'tiktok' => 'ATHENASBOUTIQUE1',
        'email' => 'athenasboutique20@gmail.com',
        'whatsapp_number' => '584124652070',
        'whatsapp_display' => '+58 412-4652070',
        'whatsapp_message_intro' => 'Hola Athenas Boutique, quiero comprar estos productos:',
    ],
    'currency' => [
        'code' => 'EUR',
        'symbol' => 'EUR',
        'prefix' => 'EUR ',
    ],
    'category_labels' => [
        'earrings' => 'Aretes',
        'rings' => 'Anillos',
        'necklaces' => 'Collares',
    ],
    'color_swatches' => [
        'dorado' => ['label' => 'Dorado', 'hex' => '#d4a532'],
        'plateado' => ['label' => 'Plateado', 'hex' => '#cbd5e1'],
        'blanco' => ['label' => 'Blanco', 'hex' => '#f8fafc'],
        'negro' => ['label' => 'Negro', 'hex' => '#111827'],
        'azul' => ['label' => 'Azul', 'hex' => '#93c5fd'],
        'verde' => ['label' => 'Verde', 'hex' => '#86efac'],
        'rosa' => ['label' => 'Rosa', 'hex' => '#f9a8d4'],
        'rojo' => ['label' => 'Rojo', 'hex' => '#ef4444'],
        'naranja' => ['label' => 'Naranja', 'hex' => '#fb923c'],
        'perla' => ['label' => 'Perla', 'hex' => '#f5f5f4'],
    ],
    'materials' => [
        'Aleacion de cinc',
        'Chapado',
    ],
    'hero_images' => [
        ['src' => '/images/AthenasCodex/catalog-cover.png', 'alt' => 'Portada del catalogo Athenas Boutique'],
        ['src' => '/images/AthenasCodex/catalog-earrings.png', 'alt' => 'Pagina de aretes del catalogo Athenas Boutique'],
        ['src' => '/images/AthenasCodex/catalog-jewelry.png', 'alt' => 'Pagina de anillos y collares del catalogo Athenas Boutique'],
    ],
    'products' => [
        ['sku' => 'dalia-wave', 'name' => 'Dalia', 'code' => 'DALIA', 'category' => 'earrings', 'price' => 1.5, 'colors' => ['plateado'], 'available' => true, 'featured' => true],
        ['sku' => 'jada-twist', 'name' => 'Jada', 'code' => 'JADA', 'category' => 'earrings', 'price' => 1.5, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'artis-geo', 'name' => 'Artis', 'code' => 'ARTIS', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'hada-basic', 'name' => 'Hada', 'code' => 'HADA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'patrice-mini', 'name' => 'Patrice', 'code' => 'PATRICE', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['azul'], 'available' => true, 'featured' => false],
        ['sku' => 'agnes-duo', 'name' => 'Agnes', 'code' => 'AGNES', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['azul', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'thalia-heart', 'name' => 'Thalia', 'code' => 'THALIA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'artemisa-pearl', 'name' => 'Artemisa', 'code' => 'ARTEMISA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'persefone-hoop', 'name' => 'Persefone', 'code' => 'PERSEFONE', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'selene-knot', 'name' => 'Selene', 'code' => 'SELENE', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'euriclea-heart', 'name' => 'Euriclea', 'code' => 'EURICLEA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'calista-flower', 'name' => 'Calista Flor', 'code' => 'CALISTA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'isidora-leaf', 'name' => 'Isidora', 'code' => 'ISIDORA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado', 'azul'], 'available' => true, 'featured' => false],
        ['sku' => 'liliana-cuff', 'name' => 'Liliana', 'code' => 'LILIANA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'dora-chain', 'name' => 'Dora', 'code' => 'DORA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'calista-braid', 'name' => 'Calista Hoops', 'code' => 'CALISTA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'xena-texture', 'name' => 'Xena', 'code' => 'XENA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'gretel-trio', 'name' => 'Gretel', 'code' => 'GRETEL', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'elaila-wave', 'name' => 'Elaila', 'code' => 'ELAILA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'helena-slim', 'name' => 'Helena Slim', 'code' => 'HELENA', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'mek-chunky', 'name' => 'Mek', 'code' => 'MEK', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'melissa-link', 'name' => 'Melissa', 'code' => 'MELISSA', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'delta-texture', 'name' => 'Delta', 'code' => 'DELTA', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado'], 'available' => true, 'featured' => true],
        ['sku' => 'irene-heart', 'name' => 'Irene', 'code' => 'IRENE', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'kalliope-stack', 'name' => 'Kalliope', 'code' => 'KALLIOPE', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'calipso-bow', 'name' => 'Calipso', 'code' => 'CALIPSO', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'xenia-zigzag', 'name' => 'Xenia', 'code' => 'XENIA', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'cora-duotone', 'name' => 'Cora', 'code' => 'CORA', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'euridice-crystal', 'name' => 'Euridice', 'code' => 'EURIDICE', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'thais-heart', 'name' => 'Thais', 'code' => 'THAIS', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['blanco', 'rosa', 'azul'], 'available' => true, 'featured' => false],
        ['sku' => 'melina-mini', 'name' => 'Melina', 'code' => 'MELINA', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'eirene-dome', 'name' => 'Eirene', 'code' => 'EIRENE', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'thetis-bold', 'name' => 'Thetis', 'code' => 'THETIS', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'sophiana-cross', 'name' => 'Sophiana', 'code' => 'SOPHIANA', 'category' => 'rings', 'price' => 2.5, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'amal-pop', 'name' => 'Amal', 'code' => 'AMAL', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['azul', 'verde', 'naranja'], 'available' => true, 'featured' => false],
        ['sku' => 'jade-green', 'name' => 'Jade', 'code' => 'JADE', 'category' => 'earrings', 'price' => 2.5, 'colors' => ['verde'], 'available' => true, 'featured' => false],
        ['sku' => 'piram-triangle', 'name' => 'Piram', 'code' => 'PIRAM', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'ariana-pearl', 'name' => 'Ariana', 'code' => 'ARIANA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'ariadna-square', 'name' => 'Ariadna', 'code' => 'ARIADNA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['blanco'], 'available' => true, 'featured' => false],
        ['sku' => 'kallista-drape', 'name' => 'Kallista', 'code' => 'KALLISTA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'talia-blue', 'name' => 'Talia', 'code' => 'TALIA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['azul'], 'available' => true, 'featured' => false],
        ['sku' => 'nefeli-loop', 'name' => 'Nefeli', 'code' => 'NEFELI', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'leonidas-bold', 'name' => 'Leonidas', 'code' => 'LEONIDAS', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => true],
        ['sku' => 'phaedra-link', 'name' => 'Phaedra', 'code' => 'PHAEDRA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'orestes-knot', 'name' => 'Orestes', 'code' => 'ORESTES', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'iris-silver', 'name' => 'Iris', 'code' => 'IRIS', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'psyche-braid', 'name' => 'Psyche', 'code' => 'PSYCHE', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'philomena-semi', 'name' => 'Philomena', 'code' => 'PHILOMENA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'urania-rounded', 'name' => 'Urania', 'code' => 'URANIA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'xanthipe-ribbed', 'name' => 'Xanthipe', 'code' => 'XANTHIPE', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'kalli-link', 'name' => 'Kalli', 'code' => 'KALLI', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'isidra-stack', 'name' => 'Isidra', 'code' => 'ISIDRA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'demoste-pin', 'name' => 'Demoste', 'code' => 'DEMOSTE', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'apollo-drop', 'name' => 'Apollo', 'code' => 'APOLLO', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'medea-flower', 'name' => 'Medea', 'code' => 'MEDEA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'also-sculpt', 'name' => 'Also', 'code' => 'ALSO', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'mintris-shell', 'name' => 'Mintris', 'code' => 'MINTRIS', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'fedra-triple', 'name' => 'Fedra', 'code' => 'FEDRA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'damaris-petal', 'name' => 'Damaris', 'code' => 'DAMARIS', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'caliope-curve', 'name' => 'Caliope', 'code' => 'CALIOPE', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'aspasia-multi', 'name' => 'Aspasia', 'code' => 'ASPASIA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['plateado', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'helena-square', 'name' => 'Helena Geometrica', 'code' => 'HELENA', 'category' => 'earrings', 'price' => 3.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'eleni-disc', 'name' => 'Eleni', 'code' => 'ELENI', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'gaia-butterfly', 'name' => 'Gaia', 'code' => 'GAIA', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'cassia-climber', 'name' => 'Cassia', 'code' => 'CASSIA', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'penelope-fan', 'name' => 'Penelope', 'code' => 'PENELOPE', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'circe-sun', 'name' => 'Circe', 'code' => 'CIRCE', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'eatis-half', 'name' => 'Eatis', 'code' => 'EATIS', 'category' => 'earrings', 'price' => 3.5, 'colors' => ['dorado'], 'available' => false, 'featured' => false],
        ['sku' => 'chloris-heart', 'name' => 'Chloris', 'code' => 'CHLORIS', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'eva-tassel', 'name' => 'Eva', 'code' => 'EVA', 'category' => 'earrings', 'price' => 4.0, 'colors' => ['negro'], 'available' => true, 'featured' => false],
        ['sku' => 'alexandros-link', 'name' => 'Alexandros', 'code' => 'ALEXANDROS', 'category' => 'earrings', 'price' => 5.0, 'colors' => ['dorado', 'plateado'], 'available' => false, 'featured' => false],
        ['sku' => 'chrysothemis-organic', 'name' => 'Chrysothemis', 'code' => 'CHRYSOTHEMIS', 'category' => 'earrings', 'price' => 5.0, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'caiena-flower', 'name' => 'Caiena', 'code' => 'CAIENA', 'category' => 'earrings', 'price' => 8.0, 'colors' => ['dorado'], 'available' => true, 'featured' => true],
        ['sku' => 'jupiter-fan', 'name' => 'Jupiter', 'code' => 'JUPITER', 'category' => 'earrings', 'price' => 8.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'panagiotis-disc', 'name' => 'Panagiotis', 'code' => 'PANAGIOTIS', 'category' => 'earrings', 'price' => 5.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'thomas-burst', 'name' => 'Thomas', 'code' => 'THOMAS', 'category' => 'earrings', 'price' => 8.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'agamen-cuff', 'name' => 'Agamen', 'code' => 'AGAMEN', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'bolls-sphere', 'name' => 'Bolls', 'code' => 'BOLLS', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'espiral-cuff', 'name' => 'Espiral Cuff', 'code' => 'ESPIRAL', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'tyche-trio', 'name' => 'Tyche', 'code' => 'TYCHE', 'category' => 'earrings', 'price' => 2.0, 'colors' => ['plateado', 'rosa', 'dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'pyram-cuff', 'name' => 'Pyram', 'code' => 'PYRAM', 'category' => 'earrings', 'price' => 5.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'pasiphae-ring', 'name' => 'Pasiphae', 'code' => 'PASIPHAE', 'category' => 'rings', 'price' => 3.5, 'colors' => ['dorado', 'plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'set-2-rings', 'name' => 'Set 2', 'code' => 'SET 2', 'category' => 'rings', 'price' => 5.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'set-4-rings', 'name' => 'Set 4', 'code' => 'SET 4', 'category' => 'rings', 'price' => 8.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'set-3-rings', 'name' => 'Set 3', 'code' => 'SET 3', 'category' => 'rings', 'price' => 5.0, 'colors' => ['dorado'], 'available' => true, 'featured' => false],
        ['sku' => 'ava-ring', 'name' => 'Ava', 'code' => 'AVA', 'category' => 'rings', 'price' => 4.0, 'colors' => ['dorado', 'plateado'], 'available' => false, 'featured' => false],
        ['sku' => 'perla-ring', 'name' => 'Perla', 'code' => 'PERLA', 'category' => 'rings', 'price' => 3.0, 'colors' => ['dorado', 'perla'], 'available' => true, 'featured' => false],
        ['sku' => 'artemis-ring', 'name' => 'Artemis', 'code' => 'ARTEMIS', 'category' => 'rings', 'price' => 2.0, 'colors' => ['plateado'], 'available' => true, 'featured' => false],
        ['sku' => 'espiral-ring', 'name' => 'Espiral Ring', 'code' => 'ESPIRAL', 'category' => 'rings', 'price' => 2.0, 'colors' => ['dorado', 'plateado'], 'available' => false, 'featured' => false],
        ['sku' => 'alexander-chain', 'name' => 'Alexander', 'code' => 'ALEXANDER', 'category' => 'necklaces', 'price' => 6.0, 'colors' => ['dorado'], 'available' => false, 'featured' => false],
        ['sku' => 'mystic-layered', 'name' => 'Mystic', 'code' => 'MYSTIC', 'category' => 'necklaces', 'price' => 5.0, 'colors' => ['dorado'], 'available' => true, 'featured' => true],
        ['sku' => 'spyros-pendant', 'name' => 'Spyros', 'code' => 'SPYROS', 'category' => 'necklaces', 'price' => 3.5, 'colors' => ['rojo', 'dorado'], 'available' => true, 'featured' => false],
    ],
];
